<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="PC155" failures="1" tests="1" name="ede_partner_testcases.TestCase_39" time="1050.919" errors="0" timestamp="2022-04-21T01:19:54 PKT" skipped="0">
  <testcase classname="ede_partner_testcases.TestCase_39" name="testCase_39" time="1050.919">
    <failure message="Failed to verify: Did any of these people lose qualifying health coverage between Feb 19, 2022 and Apr 20, 2022? expected [Did any of these people lose qualifying health coverage between Feb 20, 2022 and Apr 21, 2022?] but found [Did any of these people lose qualifying health coverage between Feb 19, 2022 and Apr 20, 2022?]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Failed to verify: Did any of these people lose qualifying health coverage between Feb 19, 2022 and Apr 20, 2022? expected [Did any of these people lose qualifying health coverage between Feb 20, 2022 and Apr 21, 2022?] but found [Did any of these people lose qualifying health coverage between Feb 19, 2022 and Apr 20, 2022?]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.assertEqualsImpl(Assert.java:136)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:575)
at pages.CommonMethodPage.verifyS083(CommonMethodPage.java:1390)
at ede_partner_testcases.TestCase_39.testCase_39(TestCase_39.java:693)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:597)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:766)
at org.testng.TestRunner.run(TestRunner.java:587)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1109)
at org.testng.TestNG.runSuites(TestNG.java:1039)
at org.testng.TestNG.run(TestNG.java:1007)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- testCase_39 -->
  <system-out/>
</testsuite> <!-- ede_partner_testcases.TestCase_39 -->
